# Generated by Django 3.2 on 2022-05-25 23:03

import cloudinary.models
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, unique=True)),
                ('last_name', models.CharField(max_length=50)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None)),
                ('image', cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image')),
            ],
        ),
    ]
