# Generated by Django 3.2 on 2022-05-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylist',
            name='years_experience',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
