# Generated by Django 3.2 on 2022-05-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stylist',
            name='price',
        ),
        migrations.AlterField(
            model_name='stylist',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
    ]
