# Generated by Django 3.2 on 2022-05-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylists', '0002_stylist_years_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylist',
            name='background_details',
            field=models.CharField(default='', max_length=250),
        ),
    ]
