# Generated by Django 3.2 on 2022-05-03 06:21

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('stylists', '0002_auto_20220503_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylist',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
