# Generated by Django 3.2 on 2022-05-03 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stylists', '0003_alter_stylist_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stylist',
            name='telephone',
        ),
    ]
