# Generated by Django 3.2 on 2022-05-03 07:17

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('stylists', '0004_remove_stylist_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylist',
            name='telephone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
