# Generated by Django 3.2 on 2022-05-03 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stylists', '0005_stylist_telephone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stylist',
            unique_together={('first_name', 'last_name')},
        ),
    ]
