# Generated by Django 3.2 on 2022-05-06 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stylists', '0007_stylist_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stylist',
            name='telephone',
        ),
    ]
