# Generated by Django 3.2 on 2022-05-06 21:06

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('stylists', '0009_alter_stylist_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylist',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None),
        ),
    ]
