# Generated by Django 3.2 on 2022-05-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylists', '0010_alter_stylist_tel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stylist',
            old_name='tel',
            new_name='telephone',
        ),
        migrations.AddField(
            model_name='stylist',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
