# Generated by Django 3.2 on 2022-05-06 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylists', '0011_auto_20220506_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylist',
            name='postcode',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='stylist',
            name='street_address_1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='stylist',
            name='street_address_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stylist',
            name='town_or_city',
            field=models.CharField(default='', max_length=50),
        ),
    ]
