# Generated by Django 3.2 on 2022-05-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylists', '0012_auto_20220506_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylist',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
