# Generated by Django 3.2 on 2022-05-07 15:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stylists', '0013_stylist_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylist',
            name='image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='hairdresser-1'),
        ),
    ]
