# Generated by Django 3.2 on 2022-05-07 15:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stylists', '0014_stylist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylist',
            name='image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
        ),
    ]
