# Generated by Django 3.2 on 2022-05-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylists', '0015_alter_stylist_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stylist',
            old_name='description',
            new_name='background',
        ),
        migrations.AlterField(
            model_name='stylist',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
    ]
