# Generated by Django 3.2 on 2022-05-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylists', '0016_auto_20220507_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylist',
            name='first_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='stylist',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='stylist',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='stylist',
            name='street_address_1',
        ),
        migrations.RemoveField(
            model_name='stylist',
            name='street_address_2',
        ),
        migrations.RemoveField(
            model_name='stylist',
            name='town_or_city',
        ),
    ]
