# Generated by Django 3.2 on 2022-05-07 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylists', '0017_auto_20220507_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylist',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
