# Generated by Django 3.2 on 2022-05-01 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('CUT', 'cut'), ('COLOUR', 'colour'), ('TREATMENT', 'treatment')], default='CUT', max_length=10),
        ),
    ]
