# Generated by Django 3.2 on 2022-05-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C')], default='a', max_length=10),
        ),
    ]
