# Generated by Django 3.2 on 2022-05-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('a', 'cut'), ('b', 'colour'), ('c', 'style')], default='a', max_length=10),
        ),
    ]
