# Generated by Django 3.2 on 2022-05-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_service_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('CUT', 'cut'), ('COLOUR', 'colour'), ('STYLE', 'style')], default='CUT', max_length=10),
        ),
    ]
