# Generated by Django 3.2 on 2022-06-07 13:14

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20220502_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('20.00')), django.core.validators.MaxValueValidator(Decimal('300.00'))]),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('CUT', 'cut'), ('COLOUR', 'colour'), ('STYLE', 'style')], max_length=10),
        ),
    ]
