# Generated by Django 3.2 on 2022-06-04 22:51

import bookings.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stylists', '0003_stylist_background_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0005_auto_20220502_0359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(validators=[bookings.models.Timeslot.validate_date])),
                ('time', models.IntegerField(choices=[(0, '6PM'), (1, '7PM'), (2, '8PM'), (3, '9PM')])),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('stylist', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='stylists.stylist')),
            ],
            options={
                'unique_together': {('date', 'time', 'stylist')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('service', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.service')),
                ('timeslot', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='bookings.timeslot', validators=[bookings.models.Booking.validate_timeslot])),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='booking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
