# Generated by Django 3.2 on 2022-05-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stylists', '0018_alter_stylist_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('stylist', models.ManyToManyField(to='stylists.Stylist')),
            ],
        ),
    ]
