# Generated by Django 3.2 on 2022-05-12 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stylists', '0018_alter_stylist_email'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='stylist',
        ),
        migrations.AddField(
            model_name='appointment',
            name='stylist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stylists.stylist'),
        ),
    ]
