# Generated by Django 3.2 on 2022-06-04 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20220502_0359'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='service',
            field=models.ForeignKey(default=50, on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
    ]
