# Generated by Django 3.2 on 2022-05-12 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stylists', '0018_alter_stylist_email'),
        ('bookings', '0002_auto_20220512_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='stylist',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='stylists.stylist'),
        ),
    ]
