# Generated by Django 3.2 on 2022-05-30 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20220529_1829'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='stylist',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
    ]
