# Generated by Django 3.2 on 2022-05-30 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stylists', '0003_stylist_background_details'),
        ('bookings', '0003_auto_20220530_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('stylist', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='stylists.stylist')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='bookings.timeslot'),
        ),
    ]
